### ISSUE TITLE
"java.lang.RuntimeException: Instrumentation Filed!" while trying to execute the Back-end

### ISSUE THREAD

**Issue by arcanoid** [wtchoi/SwiftHand#7]
I have just started to work with SwiftHand and while following your guide for using it, I am getting the following error when trying to execute step 3 in "Using the Back-End".

Some avd info are:
- Name: Nexus_S_API_21
- Device: Nexus S (Google)
- Path: .../.android/avd/Nexus_S_API_21.avd
- Target: Android 5.0.1 (API level 21)
- Tag/ABI: default/armeabi-v7a
- Skin: nexus_s
- Sdcard: 100M
- Snapshot: no

```
INFO: Error starting command: monkey --port 12345
com.android.ddmlib.ShellCommandUnresponsiveException
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:510)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:387)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:356)
    at com.android.ddmlib.Device.executeShellCommand(Device.java:547)
    at com.android.chimpchat.adb.AdbChimpDevice$1.run(AdbChimpDevice.java:105)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

send wake up!
send wake up!
wait
1trial.
Connected!
go
Waiting for initial information report
Waiting for application to be stable
application crashed! : false
Error!
java.lang.RuntimeException: Instrumentation Filed!
    at edu.berkeley.wtchoi.swift.driver.Driver.initiateApp(Driver.java:187)
    at edu.berkeley.wtchoi.swift.driver.Driver.startApp(Driver.java:125)
    at edu.berkeley.wtchoi.swift.testing.android.TargetApplication.init(TargetApplication.java:123)
    at edu.berkeley.wtchoi.swift.testing.Testing.run(Testing.java:75)
    at edu.berkeley.wtchoi.swift.testing.android.runners.TestRunner.runTesting(TestRunner.java:117)
    at edu.berkeley.wtchoi.swift.CommandLine.main(CommandLine.java:129)
Caused by: edu.berkeley.wtchoi.swift.driver.InstrumentationCrash
    at edu.berkeley.wtchoi.swift.driver.Driver.waitApplicationToBeStable(Driver.java:238)
    at edu.berkeley.wtchoi.swift.driver.Driver.initiateApp(Driver.java:181)
    ... 5 more
jp.gr.java_conf.hatalab.mnv_0
../some
java.lang.NullPointerException
    at edu.berkeley.wtchoi.swift.testing.android.learning.LearningTestingObserver.dumpOptional(LearningTestingObserver.java:67)
    at edu.berkeley.wtchoi.swift.testing.android.AppTestingObserver.dumpFinalResult(AppTestingObserver.java:247)
    at edu.berkeley.wtchoi.swift.testing.android.AppTestingObserver.onException(AppTestingObserver.java:336)
    at edu.berkeley.wtchoi.swift.testing.Testing.invokeObserveOnException(Testing.java:213)
    at edu.berkeley.wtchoi.swift.testing.Testing.run(Testing.java:93)
    at edu.berkeley.wtchoi.swift.testing.android.runners.TestRunner.runTesting(TestRunner.java:117)
    at edu.berkeley.wtchoi.swift.CommandLine.main(CommandLine.java:129)
Cannot make a log file
+ (( 0 > 0 ))
```

**Comment by wtchoi** [comment]
Hi Arcanoid,
Could you let me know which application you tried?

**Comment by arcanoid** [comment]
Hello,

My exact command was 

```
./test.sh dist/benchmark/mininote.modified.apk swift 3600 0 ../results
```

**Comment by ldf92** [comment]
I have the same issue. Has this problem been solved?
