### ISSUE TITLE
Error starting monkey

### ISSUE THREAD

**Issue by andrirad** [wtchoi/SwiftHand#9]
Hi,

I try to use the back-end of SwiftHand with a real device (Nexus 5) one one of the modified APK your provide but I get the following error.

``` shell
 $ ./test.sh dist/benchmark/mininote.modified.apk swift 3600 0 /tmp/siwft -d0640a4980acd72e1
+ export ADK_ROOT=/Users/rado/android-sdk-macosx
+ ADK_ROOT=/Users/rado/android-sdk-macosx
+ export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_76.jdk/Contents/Home
+ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_76.jdk/Contents/Home
+ java -jar /Users/rado/android/android_tools/SwiftHand/src/back-end/target/back-end-0.1-jar-with-dependencies.jar dist/benchmark/mininote.modified.apk swift 3600 0 /tmp/siwft -d0640a4980acd72e1
get ChimpChat instance
get ADB
juin 25, 2015 1:00:34 PM com.android.chimpchat.ChimpManager sendMonkeyEventAndGetResponse
INFOS: Monkey Command: wake.
juin 25, 2015 1:00:38 PM com.android.chimpchat.adb.AdbChimpDevice$1 run
GRAVE: Error starting command: monkey --port 12345
com.android.ddmlib.TimeoutException
    at com.android.ddmlib.AdbHelper.read(AdbHelper.java:767)
    at com.android.ddmlib.AdbHelper.read(AdbHelper.java:735)
    at com.android.ddmlib.AdbHelper.readAdbResponse(AdbHelper.java:224)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:463)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:388)
    at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:357)
    at com.android.ddmlib.Device.executeShellCommand(Device.java:559)
    at com.android.chimpchat.adb.AdbChimpDevice$1.run(AdbChimpDevice.java:105)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

Do you have any idea on the reasons I get this? I skipped the steps on creating an emulator because I wish to use a real device. My final goal is to measure the code coverage of your approach with the coverage of other tools.

**Comment by andrirad** [comment]
I have found the reason why I got the error. There is a missing space between the option "-d" and its associated value.
